name: DocTests in Docs
on: [push]

jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - name: Install QMCseqCL 
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Run Tests
        shell: bash -l {0}
        run: |
          make doctests