name: doctests
on: [push]

jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"] # ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Install Base Dependencies 
        shell: bash -l {0}
        run: |
          pip install numpy
          pip install pytest
      - name: Install QMCseqCL 
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Prepare Doctests from Docs 
        shell: bash -l {0}
        run: |
          python prep_docs_doctests.py
      - name: Doctests in C 
        shell: bash -l {0}
        run: |
          	pytest test.index.c.txt
      - name: Install PyOpenCL
        shell: bash -l {0}
        run: |
          pip install siphash24
          pip install pyopencl
          pip install pyopencl[pocl]
      - name: PyOpenCL Device Info
        shell: bash -l {0}
        run: |
          python -c "import qmcseqcl; qmcseqcl.print_opencl_device_info()"
      - name: Doctests in OpenCL 
        shell: bash -l {0}
        run: |
          	pytest test.index.cl.txt