name: tests
on: [push]

jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-activate-base: true
      - name: Install Base Dependencies 
        shell: bash -l {0}
        run: |
          pip install numpy
          pip install pytest
          pip install sympy
      - name: Install QMCseqCL 
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Prepare Doctests from Docs 
        shell: bash -l {0}
        run: |
          python prep_docs_doctests.py
      - name: Doctests in C 
        shell: bash -l {0}
        run: |
          python -m pytest index.c.pytest.txt
      - name: Install PyOpenCL
        shell: bash -l {0}
        run: |
          pip install siphash24
          conda install pyopencl -y
          if [ "$RUNNER_OS" == "macOS" ]; then
            conda install pocl -y
            conda install ocl_icd_wrapper_apple -y 
          elif [ "$RUNNER_OS" == "Linux" ]; then
            conda install ocl-icd-system -y 
          else # "$RUNNER_OS" == "Windows"
            conda install intel-opencl-rt -y
          fi
      - name: PyOpenCL Device Info
        shell: bash -l {0}
        run: |
          python -c "import qmcseqcl; qmcseqcl.print_opencl_device_info()"
      - name: Doctests with PyOpenCL
        shell: bash -l {0}
        run: |
          pip install pytest
          python -m pytest index.cl.pytest.txt
      - name: Short Speed Tests
        shell: bash -l {0}
        run: |
          pip install pandas 
          pip install matplotlib 
          make shortspeedtests
